server:
  port: 8091
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.16.0.100:8761/eureka/
#  server:
#    port: 9001
#  endpoint:
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 172.16.0.100
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true